"""Change date fields to Date type in Requerimiento and Orden

Revision ID: 13e9a90d76f4
Revises: 5340f2f1b044
Create Date: 2025-09-07 01:55:28.757091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e9a90d76f4'
down_revision = '5340f2f1b044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('fecha_emision',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('fecha_notificacion',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('requerimiento', schema=None) as batch_op:
        batch_op.alter_column('fecha_presentacion',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requerimiento', schema=None) as batch_op:
        batch_op.alter_column('fecha_presentacion',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('fecha_notificacion',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('fecha_emision',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
