"""Add Documento model for tracking

Revision ID: 5340f2f1b044
Revises: ef83e75e6c69
Create Date: 2025-09-06 22:37:24.609673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5340f2f1b044'
down_revision = 'ef83e75e6c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('numero_doc', sa.String(length=100), nullable=False),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('fecha_doc', sa.Date(), nullable=False),
    sa.Column('remitente_destinatario', sa.String(length=200), nullable=True, comment='Quién lo envía o a quién se envía'),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_limite_respuesta', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_path', sa.String(length=300), nullable=True),
    sa.Column('documento_padre_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_padre_id'], ['documentos.id'], name=op.f('fk_documentos_documento_padre_id_documentos')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documentos_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('archivo_orden_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('requerimiento', schema=None) as batch_op:
        batch_op.alter_column('archivo_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requerimiento', schema=None) as batch_op:
        batch_op.alter_column('archivo_path',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('archivo_orden_path',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_documentos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_estado'))

    op.drop_table('documentos')
    # ### end Alembic commands ###
