"""Migración inicial con nombres de constraints

Revision ID: 6c12401b4579
Revises: 
Create Date: 2025-08-31 15:05:39.490181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c12401b4579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedor')),
    sa.UniqueConstraint('nombre', name=op.f('uq_proveedor_nombre'))
    )
    op.create_table('requerimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_requerimiento', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_presentacion', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('archivo_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requerimiento')),
    sa.UniqueConstraint('numero_requerimiento', name=op.f('uq_requerimiento_numero_requerimiento'))
    )
    op.create_table('orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('tipo_orden', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.String(length=10), nullable=True),
    sa.Column('fecha_notificacion', sa.String(length=10), nullable=True),
    sa.Column('plazo_ejecucion_dias', sa.Integer(), nullable=True),
    sa.Column('archivo_orden_path', sa.String(length=200), nullable=True),
    sa.Column('requerimiento_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], name=op.f('fk_orden_proveedor_id_proveedor')),
    sa.ForeignKeyConstraint(['requerimiento_id'], ['requerimiento.id'], name=op.f('fk_orden_requerimiento_id_requerimiento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orden')),
    sa.UniqueConstraint('requerimiento_id', name=op.f('uq_orden_requerimiento_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden')
    op.drop_table('requerimiento')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
