"""Add multi-tenant structure

Revision ID: e5a773fd3882
Revises: 6c12401b4579
Create Date: 2025-09-06 19:36:48.341061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a773fd3882'
down_revision = '6c12401b4579'
branch_labels = None
depends_on = None


# Pega este código en tu archivo de migración, reemplazando la función upgrade() original.

from alembic import op
import sqlalchemy as sa


# ... (las variables revision, down_revision, etc., se quedan como están) ...


def upgrade():
    # PASO 1: Crear la tabla de inquilinos (tenants)
    tenants_table = op.create_table('tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre único del inquilino/cliente'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
        sa.UniqueConstraint('name', name=op.f('uq_tenants_name'))
    )

    # PASO 2: Insertar un "Inquilino Principal" por defecto para tus datos existentes
    #op.bulk_insert(tenants_table,
    #[{'id': 1, 'name': 'Inquilino Principal'}]
    #)
    default_tenant_id = 1

    # PASO 3: Crear la tabla de usuarios (users)
    # (Esta tabla se borrará en una migración posterior, pero la dejamos aquí para mantener la consistencia histórica)
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)

    # PASO 4: Añadir las columnas tenant_id a las tablas existentes, permitiendo nulos TEMPORALMENTE
    op.add_column('proveedor', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('requerimiento', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('orden', sa.Column('tenant_id', sa.Integer(), nullable=True))

    # PASO 5: Actualizar TODAS las filas existentes para que pertenezcan al inquilino principal
    op.execute(f'UPDATE proveedor SET tenant_id = {default_tenant_id}')
    op.execute(f'UPDATE requerimiento SET tenant_id = {default_tenant_id}')
    op.execute(f'UPDATE orden SET tenant_id = {default_tenant_id}')

    # PASO 6: Ahora que todas las filas tienen un valor, hacemos que las columnas sean NOT NULL
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(batch_op.f('ix_proveedor_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_proveedor_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])
        # Alembic detectó que quitaste unique=True de 'nombre', lo incluimos aquí.
        batch_op.drop_constraint('uq_proveedor_nombre', type_='unique')

    with op.batch_alter_table('requerimiento', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(batch_op.f('ix_requerimiento_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_requerimiento_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])
        # Alembic detectó que quitaste unique=True de 'numero_requerimiento'.
        batch_op.drop_constraint('uq_requerimiento_numero_requerimiento', type_='unique')

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('tenant_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(batch_op.f('ix_orden_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_orden_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requerimiento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requerimiento_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requerimiento_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_requerimiento_numero_requerimiento'), ['numero_requerimiento'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_proveedor_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_proveedor_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_proveedor_nombre'), ['nombre'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orden_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orden_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
